services:
  fundy:
    build: .
    container_name: fundy
    ports:
      - "${SERVER_PORT_EXTERNAL:-8080}:${SERVER_PORT_INTERNAL:-8080}"
    environment:
      - SERVER_HOST${HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT_INTERNAL:-8080}
      - SPRING_PROFILES_ACTIVE=${SERVER_SPRING_PROFILE:-local}
      - TELEGRAM_USERNAME={TELEGRAM_USERNAME}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${SERVER_HOST}:${SERVER_PORT_INTERNAL}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-net:
    driver: bridge
