services:
  fundy:
    build: .
    container_name: fundy
    ports:
      - "${SERVER_PORT_EXTERNAL:-8080}:${SERVER_PORT_INTERNAL:-8080}"
    environment:
      - SERVER_PORT=${SERVER_PORT_INTERNAL:-8080}
      - SPRING_PROFILES_ACTIVE=${SERVER_SPRING_PROFILE:-local}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT_INTERNAL=${REDIS_PORT_INTERNAL:-6379}
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${SERVER_HOST}:${SERVER_PORT_INTERNAL}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.4.5-alpine3.21
    container_name: redis
    ports:
      - "${REDIS_PORT_EXTERNAL:-6379}:${REDIS_PORT_INTERNAL:-6379}"
    restart: unless-stopped
    networks:
      - app-net
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-net:
    driver: bridge

volumes:
  redis_data:
