spring:
  application:
    name: Fundy
  cache:
    type: caffeine
    cache-names:
      - ex-instruments
      - ex-tickers
      - ex-funding-meta
    caffeine:
      spec: maximumSize=2000,expireAfterWrite=30s

server:
  port: ${SERVER_PORT_INTERNAL}

logging:
  level:
    root: info
    org.hibernate: warn
    org.hibernate.SQL: warn
    org.springframework.boot.actuate: warn

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

fundy:
  feedback:
    telegram:
      token: ${FEEDBACK_TG_TOKEN:}
      chat-id: ${FEEDBACK_TG_CHAT_ID:}
  cache:
    exchange:
      instruments-ttl: 30m
      instruments-max-size: 5000
      tickers-ttl: 2s
      tickers-max-size: 50000
      funding-ttl: 90s
      funding-max-size: 50000
  exchanges:
    bybit:
      api-key: ${BYBIT_API_KEY}
      secret-key: ${BYBIT_SECRET_KEY}
      base-url: https://api.bybit.com
      timeout: 30
      enabled: true
    mexc:
      api-key: ${MEXC_API_KEY}
      secret-key: ${MEXC_SECRET_KEY}
      base-url: https://contract.mexc.com
      timeout: 30
      enabled: true
    kucoin:
      api-key: ${KUCOIN_API_KEY}
      secret-key: ${KUCOIN_SECRET_KEY}
      base-url: https://api-futures.kucoin.com
      timeout: 30
      enabled: true
    bitget:
      api-key: ${BITGET_API_KEY}
      secret-key: ${BITGET_SECRET_KEY}
      base-url: https://api.bitget.com
      timeout: 30
      enabled: true
      product-type: umcbl
    bingx:
      api-key: ${BINGX_API_KEY}
      secret-key: ${BINGX_SECRET_KEY}
      base-url: https://open-api.bingx.com
      timeout: 30
      enabled: true
    okx:
      api-key: ${OKX_API_KEY}
      secret-key: ${OKX_SECRET_KEY}
      base-url: https://www.okx.com
      timeout: 30
      enabled: true
    gateio:
      api-key: ${GATEIO_API_KEY}
      secret-key: ${GATEIO_SECRET_KEY}
      base-url: https://api.gateio.ws
      settle: usdt
      timeout: 30
      enabled: true
    coinex:
      api-key: ${COINEX_API_KEY}
      secret-key: ${COINEX_SECRET_KEY}
      base-url: https://api.coinex.com
      timeout: 30
      enabled: true
    htx:
      api-key: ${HTX_API_KEY}
      secret-key: ${HTX_SECRET_KEY}
      base-url: https://api.hbdm.com
      timeout: 30
      enabled: true