spring:
  application:
    name: Fundy

server:
  port: 8082

logging:
  level:
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true