spring:
  application:
    name: Fundy
  cache:
    type: redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT_INTERNAL}

fundy:
  exchanges:
    bybit:
      enabled: false
      apiKey: ""
      secretKey: ""
      baseUrl: "https://api.bybit.com"
      timeout: 10

server:
  port: 8082

logging:
  level:
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true