spring:
  application:
    name: Fundy
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT_INTERNAL}/${DB_NAME}
#    password: ${POSTGRES_PASSWORD}
#    username: ${POSTGRES_USER}
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: none
#    show-sql: false
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    drop-first: false
#    enabled: true
#    parameters:
#      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID:0}
  cache:
    type: caffeine

telegram.bot:
  username: ${TELEGRAM_USERNAME}
  token: ${TELEGRAM_TOKEN}

server:
  port: ${SERVER_PORT_INTERNAL}

logging:
  level:
    root: info
    org.hibernate: warn
    org.hibernate.SQL: warn
    org.springframework.boot.actuate: warn

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

fundy:
  exchanges:
    bybit:
      api-key: ${BYBIT_API_KEY}
      secret-key: ${BYBIT_SECRET_KEY}
      base-url: https://api.bybit.com
      timeout: 10
      enabled: true
    mexc:
      api-key: ${MEXC_API_KEY}
      secret-key: ${MEXC_SECRET_KEY}
      base-url: https://contract.mexc.com
      timeout: 10
      enabled: true
    kucoin:
      api-key: ${KUCOIN_API_KEY}
      secret-key: ${KUCOIN_SECRET_KEY}
      base-url: https://api-futures.kucoin.com
      timeout: 10
      enabled: true
    bitget:
      api-key: ${BITGET_API_KEY}
      secret-key: ${BITGET_SECRET_KEY}
      base-url: https://api.bitget.com
      timeout: 10
      enabled: true
      product-type: umcbl
    bingx:
      api-key: ${BINGX_API_KEY}
      secret-key: ${BINGX_SECRET_KEY}
      base-url: https://open-api.bingx.com
      timeout: 10
      enabled: true
    okx:
      api-key: ${OKX_API_KEY}
      secret-key: ${OKX_SECRET_KEY}
      base-url: https://www.okx.com
      timeout: 10
      enabled: true
    gateio:
      api-key: ${GATEIO_API_KEY}
      secret-key: ${GATEIO_SECRET_KEY}
      base-url: https://api.gateio.ws
      settle: usdt
      timeout: 10
      enabled: true
    coinex:
      api-key: ${COINEX_API_KEY}
      secret-key: ${COINEX_SECRET_KEY}
      base-url: https://api.coinex.com
      timeout: 10
      enabled: true
    htx:
      api-key: ${HTX_API_KEY}
      secret-key: ${HTX_SECRET_KEY}
      base-url: https://api.hbdm.com
      timeout: 10
      enabled: true
  notifier:
    scan-delay: PT2M