spring:
  application:
    name: Fundy
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT_INTERNAL:6379}

fundy:
  exchanges:
    bybit:
      api-key: ${BYBIT_API_KEY:}
      secret-key: ${BYBIT_SECRET_KEY:}
      base-url: https://api.bybit.com
      timeout: 10
      enabled: true
    mexc:
      api-key: ${MEXC_API_KEY:}
      secret-key: ${MEXC_SECRET_KEY:}
      base-url: https://contract.mexc.com
      timeout: 10
      enabled: true

server:
  port: 8082

logging:
  level:
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true