export const EUROPE_TIMEZONES: string[] = [
    'Europe/Lisbon',
    'Europe/Dublin',
    'Europe/London',
    'Atlantic/Reykjavik',

    'Europe/Madrid',
    'Europe/Paris',
    'Europe/Brussels',
    'Europe/Amsterdam',
    'Europe/Berlin',
    'Europe/Copenhagen',
    'Europe/Oslo',
    'Europe/Stockholm',
    'Europe/Vienna',
    'Europe/Zurich',
    'Europe/Rome',

    'Europe/Warsaw',
    'Europe/Prague',
    'Europe/Budapest',
    'Europe/Bratislava',
    'Europe/Ljubljana',
    'Europe/Zagreb',
    'Europe/Belgrade',
    'Europe/Sarajevo',
    'Europe/Podgorica',
    'Europe/Tirane',

    'Europe/Sofia',
    'Europe/Bucharest',
    'Europe/Chisinau',
    'Europe/Athens',
    'Europe/Nicosia',

    'Europe/Tallinn',
    'Europe/Riga',
    'Europe/Vilnius',
    'Europe/Helsinki',

    'Europe/Kaliningrad',
    'Europe/Kyiv',
    'Europe/Minsk',
    'Europe/Istanbul',
    'Europe/Moscow',
];

export const BASE_TIMEZONES: string[] = [
    'UTC',
    'America/New_York',
    'America/Chicago',
    'America/Los_Angeles',
    'America/Sao_Paulo',
    'Asia/Dubai',
    'Asia/Singapore',
    'Asia/Hong_Kong',
    'Asia/Shanghai',
    'Asia/Seoul',
    'Asia/Tokyo',
];
