name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fundy:latest

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          GHCR_PAT: ${{ secrets.REGISTRY_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: GHCR_PAT
          script: |
            set -e
            WORKDIR=/home/prots/fundy

            [ -d "$WORKDIR/.git" ] || git clone https://github.com/protsenkopavel/Fundy "$WORKDIR"
            cd "$WORKDIR"
            git pull --ff-only

            [ -f .env ] || { echo ".env не найден – abort"; exit 1; }

            echo "$GHCR_PAT" | docker login ghcr.io -u protsenkopavel --password-stdin

            docker compose -f compose.yaml -f compose.prod.yaml pull
            docker compose -f compose.yaml -f compose.prod.yaml up -d --remove-orphans
            docker image prune -f